# Generated by Django 4.2.8 on 2026-04-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shiftinstance')),
            ],
            options={
                'verbose_name': 'Đăng ký lịch làm',
                'verbose_name_plural': 'Đăng ký lịch làm',
                'db_table': 'schedule_registration',
                'unique_together': {('employee', 'shift_instance')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.IntegerField(verbose_name='ID vị trí')),
                ('max_quantity', models.IntegerField(default=0, verbose_name='Số lượng tối đa')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shiftinstance')),
            ],
            options={
                'verbose_name': 'Sức chứa lịch làm',
                'verbose_name_plural': 'Sức chứa lịch làm',
                'db_table': 'schedule_capacity',
                'unique_together': {('position_id', 'shift_instance')},
            },
        ),
    ]
