# Generated by Django 4.2.8 on 2026-04-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shiftinstance', verbose_name='Ca đăng ký')),
            ],
            options={
                'unique_together': {('employee', 'shift_instance')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quantity', models.PositiveIntegerField(verbose_name='Số lượng tối đa')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí')),
                ('shift_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shiftinstance', verbose_name='Phiên làm việc')),
            ],
            options={
                'unique_together': {('position', 'shift_instance')},
            },
        ),
    ]
