# Generated by Django 4.2.8 on 2026-04-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('payroll_period', models.CharField(max_length=7, verbose_name='Kỳ lương (MM-YYYY)')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng lương')),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng thưởng')),
                ('total_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng phạt')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Lương thực nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Bảng lương',
                'db_table': 'payroll',
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_level_id', models.IntegerField(verbose_name='ID bậc lương')),
                ('level_name', models.CharField(max_length=100, verbose_name='Tên bậc lương')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lương cơ bản')),
                ('group_id', models.IntegerField(default=1, verbose_name='ID nhóm')),
                ('effective_date', models.DateField(auto_now_add=True, verbose_name='Ngày hiệu lực')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Chi tiết lương',
                'verbose_name_plural': 'Chi tiết lương',
                'db_table': 'salary_detail',
                'unique_together': {('employee', 'salary_level_id')},
            },
        ),
    ]
