# Generated by Django 4.2.8 on 2026-04-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryLevel',
            fields=[
                ('salary_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(max_length=100, verbose_name='Level Name')),
                ('pay_type', models.CharField(choices=[('HOURLY', 'Hourly Wage'), ('MONTHLY', 'Fixed Monthly Salary')], default='HOURLY', max_length=10, verbose_name='Pay Type')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Salary')),
                ('status', models.CharField(choices=[('probation', 'Probation'), ('official', 'Official')], default='probation', max_length=20, verbose_name='Status')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Salary Level',
                'verbose_name_plural': 'Salary Levels',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('payroll_period', models.CharField(max_length=7, verbose_name='Period (MM-YYYY)')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Net Salary')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='Employee')),
            ],
        ),
    ]
