# Generated by Django 6.0.4 on 2026-04-13 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('hire_date', models.DateField(verbose_name='Ngày vào làm')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngân hàng')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số tài khoản')),
                ('citizen_id', models.CharField(max_length=20, unique=True, verbose_name='CMND/CCCD')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'employee',
            },
        ),
    ]
