# Generated by Django 4.2.8 on 2026-04-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPenalty',
            fields=[
                ('rp_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('reward', 'Reward'), ('penalty', 'Penalty')], max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (VND)')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('date_applied', models.DateField(verbose_name='Date Applied')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Reward and Penalty',
                'verbose_name_plural': 'Rewards and Penalties',
            },
        ),
    ]
