# Generated by Django 4.2.8 on 2026-04-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPenalty',
            fields=[
                ('reward_penalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bonus', 'Thưởng'), ('penalty', 'Phạt')], max_length=10, verbose_name='Loại')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền')),
                ('applied_date', models.DateField(verbose_name='Ngày áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_penalties', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Thưởng phạt',
                'verbose_name_plural': 'Thưởng phạt',
                'db_table': 'reward_penalty',
            },
        ),
    ]
