# Generated by Django 4.2.8 on 2026-04-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(verbose_name='Ngày chấm công')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Giờ vào thực tế')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Giờ ra thực tế')),
                ('work_hours', models.FloatField(default=0, verbose_name='Số giờ làm')),
                ('late_hours', models.FloatField(default=0, verbose_name='Giờ đi muộn')),
                ('status', models.CharField(default='Present', max_length=50, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=100, verbose_name='Tên ca')),
                ('start_time', models.TimeField(verbose_name='Giờ vào')),
                ('end_time', models.TimeField(verbose_name='Giờ ra')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftInstance',
            fields=[
                ('shift_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField(verbose_name='Ngày làm')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shift', verbose_name='Ca làm')),
            ],
        ),
    ]
