# Generated by Django 4.2.8 on 2026-04-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shiftinstance', verbose_name='Ca thực tế'),
        ),
    ]
