# Generated by Django 4.2.8 on 2026-04-14 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shiftinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'position', 'shift_instance', 'attendance_date')},
        ),
    ]
