# Generated by Django 4.2.8 on 2026-04-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100, verbose_name='Tên vị trí')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('hire_date', models.DateField(verbose_name='Ngày vào làm')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngân hàng')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số tài khoản')),
                ('citizen_id', models.CharField(max_length=20, unique=True, verbose_name='CCCD')),
                ('status', models.CharField(choices=[('probation', 'Thử việc'), ('official', 'Chính thức')], default='probation', max_length=20, verbose_name='Tình trạng')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.position', verbose_name='Vị trí')),
            ],
        ),
    ]
